### ISSUE TITLE
Skipping dot files

### ISSUE THREAD

**Issue by roktas** [mweirauch/dropignore#14]
Hi,

First of all, thanks for this little tool, much appreciated.

I have a few ignore patterns for some dot files in Dropbox (i.e. `.vagrant` directories), but Dropignore seems to skip those patterns.  Am I missing something? Is there any reason for [this behaviour](https://github.com/mweirauch/dropignore/blob/master/src/scanner.rs#L92)?  Could it at least be an opt-out behaviour?

**Comment by mweirauch** [comment]
Hi!

First and foremost thanks!

I guess this is an oversight. The intention actually was to skip "." and ".." on _scan_ if I remember correctly. And as I didn't have the need to ignore any dot-files personally, this just slipped through.

I will have a look.

**Comment by roktas** [comment]
Thanks for the quick reply!

FWIW, here is the systemd service file I'm using.  It works great so far.

```ini
# Install dropignore to ~/.local/bin and, copy this file as ~/.config/systemd/user/dropignore.service
# (The location of Dropbox folder is ~/Dropbox, change it if necessary)
#
# Enable service:
#   systemctl --user daemon-reload
#   systemctl enable --now --user dropignore.service
#
# Make sure it works:
#   journalctl --user-unit=dropignore --follow

[Unit]
Description=Watch Dropbox folder for ignored paths
ConditionPathIsDirectory=%h/Dropbox
ConditionFileIsExecutable=%h/.local/bin/dropignore

[Service]
ExecStart=%h/.local/bin/dropignore watch %h/Dropbox
Restart=on-failure

[Install]
WantedBy=graphical.target
```

**Comment by mweirauch** [comment]
Of course my memory was wrong. The skip was not related to "." and ".." but actually to skip any possible VCS directories. It doesn't make sense to traverse e.g. ".git", ".svn", ".hg" and so on. And for not having to hardcode a list of "known VCS directories" - which might not be complete - that was the solution. I will likely change it to actually handle these filesystem entries with regard to evalution for ignoring or skipping but will try to not have them traversed/recursed any further.

Some dependency updates and stable rust fixes have to be done first. Might take a bit due to limited time.

And thanks for the systemd setup! I am running something similar for around 1.5 years without issues but never came around to document it. I will likely take a combination of yours and mine.

**Comment by roktas** [comment]
> It doesn't make sense to traverse e.g. ".git", ".svn", ".hg" and so on.

Ah, now I see.  It makes sense.  Almost all of my Git repositories are in Dropbox for years and, I've never ignored any of them. Only problem is `node_modules` like packaging cruft, which your tool aimed to fix.  BTW, your decision to centralize the configuration is also right.  I wouldn't prefer to see extra `.dropignore` files scattered around.  Ignoring files for a VCS is a dfiferent problem than ignoring files to sync for Dropbox. Extra :+1: for the proper design.

> Might take a bit due to limited time.

No problem.  Dot files are rare in my workflow (just the host dependent `.vagrant` directory, for now), I can wait.

**Comment by mweirauch** [comment]
Release [0.1.1](https://github.com/mweirauch/dropignore/releases/tag/0.1.1) is out. Hope I didn't miss something during my testing.

**Comment by roktas** [comment]
> Release [0.1.1](https://github.com/mweirauch/dropignore/releases/tag/0.1.1) is out. Hope I didn't miss something during my testing.

Sorry for the late reply.  Everything is fine on my side.  Thanks for your efforts.
