### ISSUE TITLE
Only consider directories

### ISSUE THREAD

**Issue by Hubro** [mweirauch/dropignore#21]
**Is your feature request related to a problem? Please describe.**

It seems like dropignore scans all directories *and* files and tests the pattern against all of them. If I only need to ignore directories, it would probably be a good performance optimization to only check the pattern against directories.

**Describe the solution you'd like**

An additional config option that instructs dropignore to only consider directories, for example:

```yaml
matcher:
  ignore-specs:
    - pattern: "**/node_modules"
      type: "d"
```

**Describe alternatives you've considered**

I tried using the pattern `"**/node_modules/"` (with a trailing `/`) but that didn't match anything.

**Additional context**

My Dropbox folder contains ten times as many files as directories:

```
> find ./Dropbox -type f | wc -l
445649

> find ./Dropbox -type d | wc -l
44862
```

**Comment by mweirauch** [comment]
Thanks for the detailed request @Hubro.

While scanning (file system traversal) or watching (file system notifications) the app handles the file system entries it is being passed. At that point in time it doesn't know if that file system entry is a file, a directory or a symlink. Currently the code does not retrieve this meta information from the file system (an additional IO operation) but just matches the path the file system entry carries as a property which does not need to be retrieved again.

Some simple testing with 533k entries (452k files) and warmed up caches shows a small penalty on additionally querying the file system entry type.

IMHO the matching of the path against the pattern needs to be done in any case because there might be other patterns defined which might target files.

I still think the proposal is useful to have ignore or skip specifications target only specific file system entry types. E.g. ignore a _file_ foo, but not the _directory_ foo. Actually, the matcher spec entries are objects and not just a set of strings for easier extensibility because I saw this coming one day. But even then, the path matching would very likely always be done, and only if the type property is not "any" (the default) the file systems entry type would be queried. (To safe on the expensive IO operation when not needed.)

Nevertheless, would you agree - with the explanations above - your desired goal of saving some IO operations while scanning and watching is not really possible. (Basically the traversal and file system notifications operate on file system entries no matter if the entry represents something you are interested in or not.)

**Comment by Hubro** [comment]
Makes sense to me :slightly_smiling_face: Thanks for the detailed response.

**Comment by mweirauch** [comment]
Thanks for the feedback. I have been writing a bit cryptic yesterday evening. I just want to clarify ...

On initial scanning/traversal, whenever a file system entry is encountered which matches and is by chance a directory - e.g. node_modules - it is not traversed any further, so the thousands of files in that folder are not traversed. What is happening in the watch phase though - and that leaves room for optimization - is that when a file system entry is modified _in_ an ignored directory it's not gone by unhandled but evaluated as any other file system entry allthough this would not be needed as the partent directory is ignored. It's not that of a showstopper but I will keep an eye on it.

Happy the app is useful to you.

**Comment by Hubro** [comment]
That's good to know, thanks :slightly_smiling_face:
